# Generated by Django 4.0.5 on 2022-06-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150, verbose_name='Nome do equipamento')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cracha')),
                ('matricula', models.IntegerField(verbose_name='matricula da empresa')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150, verbose_name='Nome do kit')),
                ('image', models.ImageField(upload_to='kit/%Y/%m/%d')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('status', models.CharField(choices=[('EM_USO', 'Em uso'), ('DEVOLVIDO', 'Devolvido'), ('DISPONIVEL', 'Disponivel')], default='DISPONIVEL', max_length=12, verbose_name='Status')),
                ('equipamentos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacao.equipamento', verbose_name='Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('matricula', models.IntegerField(verbose_name='Matricula do solicitante')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('FINALIZADO', 'Finalizado')], default='SOLICITADO', max_length=12, verbose_name='Solicitação')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacao.kit', verbose_name='Kit Solicitado')),
            ],
        ),
    ]
