# Generated by Django 4.0.5 on 2022-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_alter_solicitacao_data_alter_solicitacao_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
