# Generated by Django 4.0.5 on 2022-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_alter_solicitacao_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
