# Generated by Django 4.0.5 on 2022-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_alter_kit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d'),
        ),
    ]
