# Generated by Django 4.0.5 on 2022-06-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_alter_kit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='status',
            field=models.CharField(choices=[('EM_USO', 'Em uso'), ('INDISPONIVEL', 'Indisponivel'), ('DISPONIVEL', 'Disponivel')], default='DISPONIVEL', max_length=12, verbose_name='Status'),
        ),
    ]
