# Generated by Django 4.0.5 on 2022-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0008_solicitacao_hora_termino_alter_kit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='observacao',
            field=models.TextField(default='agora', verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
