# Generated by Django 4.0.5 on 2022-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0009_solicitacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
